apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-app
  template:
    metadata:
      labels:
        app: prometheus-app
    spec:
      containers:
        - name: app
          image: prometheus-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2