apiVersion: v1
kind: Service
metadata:
  name: prometheus-app
  labels:
    app: prometheus-app
    monitoring: "true"
spec:
  selector:
    app: prometheus-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000