apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: prometheus-app
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      monitoring: "true"
      app: prometheus-app
  
  namespaceSelector:
    matchNames:
      - default
  
  endpoints:
    - port: http
      path: /metrics
      interval: 10s